name: shrimpshop_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+13

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  http: ^1.2.2
  url_launcher: ^6.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.1


  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/splash.png
    - assets/home_banner.jpg
    - assets/
    - assets/news_banner.jpg
    - assets/promo_banner.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon1.png"
  adaptive_icon_background: "#0F3B57"
  adaptive_icon_foreground: "assets/icon1.png"
  remove_alpha_ios: true